language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t pp449/react-test-app -f ./frontend/dockerfile.dev ./frontend

script:
  - docker run -e CI=true pp449/react-test-app npm run test

after_success:
  - docker build -t pp449/docker-frontend ./frontend
  - docker build -t pp449/docker-backend ./backend
  - docker build -t pp449/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push pp449/docker-frontend
  - docker push pp449/docker-backend
  - docker push pp449/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-fullstack-app"
  env: "Dockerfullstackapp-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-712076026037
  bucket_path: "docker-fullstack-app"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY