version: "2.4"
services:
  frontend:
    # build:
    #   dockerfile: dockerfile.dev
    #   context: ./frontend
    image: pp449/docker-frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    mem_limit: 128m

  nginx:
    restart: always
    # build:
    #   dockerfile: dockerfile
    #   context: ./nginx
    image: pp449/docker-nginx
    ports:
      - "80:80"
    mem_limit: 128m
    links:
      - frontend
      - backend

  backend:
    # build:
    #   dockerfile: dockerfile.dev
    #   context: ./backend
    image: pp449/docker-backend
    container_name: app_backend
    volumes: 
      - /app/node_modules
      - ./backend:/app
    environment:
      MYSQL_HOST: $MYSQL_HOST
      MYSQL_USER: $MYSQL_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_PORT: $MYSQL_PORT
    mem_limit: 128m