version: "2.4"
services:
  frontend:
    # build:
    #   dockerfile: dockerfile.dev
    #   context: ./frontend
    image: pp449/docker-frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    mem_limit: 128m

  nginx:
    restart: always
    # build:
    #   dockerfile: dockerfile
    #   context: ./nginx
    image: pp449/docker-nginx
    ports:
      - "80:80"
    mem_limit: 128m
    links:
      - frontend
      - backend

  backend:
    # build:
    #   dockerfile: dockerfile.dev
    #   context: ./backend
    image: pp449/docker-backend
    container_name: app_backend
    volumes: 
      - /app/node_modules
      - ./backend:/app
    environment:
      MYSQL_HOST: docker-fullstack-mysql.cs9770jcyko8.ap-northeast-2.rds.amazonaws.com
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: johnahn777
      MYSQL_DATABASE: myapp
      MYSQL_PORT: 3306
    mem_limit: 128m